FROM alpine:latest

RUN apk add curl gcc

ENV ENV=/root/.profile

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&\
    echo ". ~/.cargo/env" >> /root/.profile

ENTRYPOINT ["sh"]
